package pojo;

import lombok.Data;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.util.Date;
@Component
@Data
public class Book {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookId
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    private Integer bookid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookName
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    private String bookname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookImage
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    private String bookimage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookCategory
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    private String bookcategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookDcb
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    private String bookdcb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookAuthor
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    private String bookauthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookPublic
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    private String bookpublic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookTitle
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    private String booktitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookYear
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    private Date bookyear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.ISBN
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    private String isbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.price
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    private BigDecimal price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookId
     *
     * @return the value of book.bookId
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    public Integer getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookId
     *
     * @param bookid the value for book.bookId
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    public void setBookid(Integer bookid) {
        this.bookid = bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookName
     *
     * @return the value of book.bookName
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    public String getBookname() {
        return bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookName
     *
     * @param bookname the value for book.bookName
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    public void setBookname(String bookname) {
        this.bookname = bookname == null ? null : bookname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookImage
     *
     * @return the value of book.bookImage
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    public String getBookimage() {
        return bookimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookImage
     *
     * @param bookimage the value for book.bookImage
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    public void setBookimage(String bookimage) {
        this.bookimage = bookimage == null ? null : bookimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookCategory
     *
     * @return the value of book.bookCategory
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    public String getBookcategory() {
        return bookcategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookCategory
     *
     * @param bookcategory the value for book.bookCategory
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    public void setBookcategory(String bookcategory) {
        this.bookcategory = bookcategory == null ? null : bookcategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookDcb
     *
     * @return the value of book.bookDcb
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    public String getBookdcb() {
        return bookdcb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookDcb
     *
     * @param bookdcb the value for book.bookDcb
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    public void setBookdcb(String bookdcb) {
        this.bookdcb = bookdcb == null ? null : bookdcb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookAuthor
     *
     * @return the value of book.bookAuthor
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    public String getBookauthor() {
        return bookauthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookAuthor
     *
     * @param bookauthor the value for book.bookAuthor
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    public void setBookauthor(String bookauthor) {
        this.bookauthor = bookauthor == null ? null : bookauthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookPublic
     *
     * @return the value of book.bookPublic
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    public String getBookpublic() {
        return bookpublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookPublic
     *
     * @param bookpublic the value for book.bookPublic
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    public void setBookpublic(String bookpublic) {
        this.bookpublic = bookpublic == null ? null : bookpublic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookTitle
     *
     * @return the value of book.bookTitle
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    public String getBooktitle() {
        return booktitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookTitle
     *
     * @param booktitle the value for book.bookTitle
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    public void setBooktitle(String booktitle) {
        this.booktitle = booktitle == null ? null : booktitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookYear
     *
     * @return the value of book.bookYear
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    public Date getBookyear() {
        return bookyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookYear
     *
     * @param bookyear the value for book.bookYear
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    public void setBookyear(Date bookyear) {
        this.bookyear = bookyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.ISBN
     *
     * @return the value of book.ISBN
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.ISBN
     *
     * @param isbn the value for book.ISBN
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn == null ? null : isbn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.price
     *
     * @return the value of book.price
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.price
     *
     * @param price the value for book.price
     *
     * @mbggenerated Fri Aug 16 18:16:38 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
}