package pojo;

public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.messageID
     *
     * @mbggenerated Tue Aug 20 11:00:14 CST 2019
     */
    private String messageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.messagebookID
     *
     * @mbggenerated Tue Aug 20 11:00:14 CST 2019
     */
    private Integer messagebookid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.messageuserID
     *
     * @mbggenerated Tue Aug 20 11:00:14 CST 2019
     */
    private String messageuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.messageuserName
     *
     * @mbggenerated Tue Aug 20 11:00:14 CST 2019
     */
    private String messageusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.messageTime
     *
     * @mbggenerated Tue Aug 20 11:00:14 CST 2019
     */
    private String messagetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message
     *
     * @mbggenerated Tue Aug 20 11:00:14 CST 2019
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.messageHand
     *
     * @mbggenerated Tue Aug 20 11:00:14 CST 2019
     */
    private String messagehand;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.messageID
     *
     * @return the value of message.messageID
     *
     * @mbggenerated Tue Aug 20 11:00:14 CST 2019
     */
    public String getMessageid() {
        return messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.messageID
     *
     * @param messageid the value for message.messageID
     *
     * @mbggenerated Tue Aug 20 11:00:14 CST 2019
     */
    public void setMessageid(String messageid) {
        this.messageid = messageid == null ? null : messageid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.messagebookID
     *
     * @return the value of message.messagebookID
     *
     * @mbggenerated Tue Aug 20 11:00:14 CST 2019
     */
    public Integer getMessagebookid() {
        return messagebookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.messagebookID
     *
     * @param messagebookid the value for message.messagebookID
     *
     * @mbggenerated Tue Aug 20 11:00:14 CST 2019
     */
    public void setMessagebookid(Integer messagebookid) {
        this.messagebookid = messagebookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.messageuserID
     *
     * @return the value of message.messageuserID
     *
     * @mbggenerated Tue Aug 20 11:00:14 CST 2019
     */
    public String getMessageuserid() {
        return messageuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.messageuserID
     *
     * @param messageuserid the value for message.messageuserID
     *
     * @mbggenerated Tue Aug 20 11:00:14 CST 2019
     */
    public void setMessageuserid(String messageuserid) {
        this.messageuserid = messageuserid == null ? null : messageuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.messageuserName
     *
     * @return the value of message.messageuserName
     *
     * @mbggenerated Tue Aug 20 11:00:14 CST 2019
     */
    public String getMessageusername() {
        return messageusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.messageuserName
     *
     * @param messageusername the value for message.messageuserName
     *
     * @mbggenerated Tue Aug 20 11:00:14 CST 2019
     */
    public void setMessageusername(String messageusername) {
        this.messageusername = messageusername == null ? null : messageusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.messageTime
     *
     * @return the value of message.messageTime
     *
     * @mbggenerated Tue Aug 20 11:00:14 CST 2019
     */
    public String getMessagetime() {
        return messagetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.messageTime
     *
     * @param messagetime the value for message.messageTime
     *
     * @mbggenerated Tue Aug 20 11:00:14 CST 2019
     */
    public void setMessagetime(String messagetime) {
        this.messagetime = messagetime == null ? null : messagetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message
     *
     * @return the value of message.message
     *
     * @mbggenerated Tue Aug 20 11:00:14 CST 2019
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message
     *
     * @param message the value for message.message
     *
     * @mbggenerated Tue Aug 20 11:00:14 CST 2019
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.messageHand
     *
     * @return the value of message.messageHand
     *
     * @mbggenerated Tue Aug 20 11:00:14 CST 2019
     */
    public String getMessagehand() {
        return messagehand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.messageHand
     *
     * @param messagehand the value for message.messageHand
     *
     * @mbggenerated Tue Aug 20 11:00:14 CST 2019
     */
    public void setMessagehand(String messagehand) {
        this.messagehand = messagehand == null ? null : messagehand.trim();
    }
}