package pojo;

public class UserBook {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbook.id
     *
     * @mbggenerated Tue Aug 20 11:00:14 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbook.uid
     *
     * @mbggenerated Tue Aug 20 11:00:14 CST 2019
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbook.bid
     *
     * @mbggenerated Tue Aug 20 11:00:14 CST 2019
     */
    private Integer bid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbook.id
     *
     * @return the value of userbook.id
     *
     * @mbggenerated Tue Aug 20 11:00:14 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbook.id
     *
     * @param id the value for userbook.id
     *
     * @mbggenerated Tue Aug 20 11:00:14 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbook.uid
     *
     * @return the value of userbook.uid
     *
     * @mbggenerated Tue Aug 20 11:00:14 CST 2019
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbook.uid
     *
     * @param uid the value for userbook.uid
     *
     * @mbggenerated Tue Aug 20 11:00:14 CST 2019
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbook.bid
     *
     * @return the value of userbook.bid
     *
     * @mbggenerated Tue Aug 20 11:00:14 CST 2019
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbook.bid
     *
     * @param bid the value for userbook.bid
     *
     * @mbggenerated Tue Aug 20 11:00:14 CST 2019
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }
}