package mapper;

import java.util.List;

import org.springframework.stereotype.Repository;
import pojo.Book;
@Repository
public interface BookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Tue Aug 20 10:50:29 CST 2019
     */
    int deleteByPrimaryKey(Integer bookid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Tue Aug 20 10:50:29 CST 2019
     */
    int insert(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Tue Aug 20 10:50:29 CST 2019
     */
    Book selectByPrimaryKey(Integer bookid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Tue Aug 20 10:50:29 CST 2019
     */
    List<Book> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Tue Aug 20 10:50:29 CST 2019
     */
    int updateByPrimaryKey(Book record);

    List<Book> selectByBookName(String bookname);
}